AWSTemplateFormatVersion: 2010-09-09

Description: S3 bucket for dbc converter

Resources:
  dbcConverterBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: dbc-converter-bucket
      AccessControl: Private
      NotificationConfiguration:
        QueueConfigurations:
        - Queue: !ImportValue "dbcConverterQueue-ARN"
          Event: "s3:ObjectCreated:*"
          Filter:
            S3Key:
              Rules:
              - Name: prefix
                Value: in
#      NotificationConfiguration:
#        LambdaConfigurations:
#          -
#            Function: !Ref LambdaDeploymentArn
#            Event: "s3:ObjectCreated:*"
#            Filter:
#              S3Key:
#                Rules:
#                  -
#                    Name: prefix
#                    Value: in

  dbcConverterBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref dbcConverterBucket
      PolicyDocument:
        Statement:
        - Action:
          - "s3:PutObject"
          Effect: "Allow"
          Resource:
            Fn::Join:
            - ""
            - - "arn:aws:s3:::"
              - Ref: "dbcConverterBucket"
              - "/*"
          Principal:
            Service:
            - ses.amazonaws.com

Outputs:
  dbcConverterBucket:
    Description: S3 Bucketname for dbc converter
    Value: !Ref dbcConverterBucket
    Export:
      Name: "dbcConverterBucket"