AWSTemplateFormatVersion: '2010-09-09'

Description: SQS

Resources:
  dbcConverterQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: "dbcConverterQueue"

  dbcConverterQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      PolicyDocument:
        Statement:
        - Action:
          - "sqs:*"
          Effect: "Allow"
          Principal:
            Service:
            - "s3.amazonaws.com"
          Resource:
            - !GetAtt dbcConverterQueue.Arn
      Queues:
        - !Ref dbcConverterQueue

Outputs:
  dbcConverterQueue:
    Description: SQS Queue for DBC Converter
    Value: !Ref dbcConverterQueue
    Export:
      Name: "dbcConverterQueue"
  dbcConverterQueueArn:
    Description: ARN of SQS Queue for DBC Converter
    Value: !GetAtt dbcConverterQueue.Arn
    Export:
      Name: "dbcConverterQueue-ARN"